### ISSUE TITLE
メンテナンス機能を実装

### ISSUE THREAD

**Issue by wheatandcat** [wheatandcat/memoir#109]
## 対応内容

一旦、リモートコンフィグが使えるか検証
https://firebase.google.com/docs/remote-config/use-config-web?hl=ja

**Comment by wheatandcat** [comment]
Remote ConfigはExpoだとエラーになるっぽい
```
ReferenceError: Can't find variable: IDBIndex
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```

**Comment by wheatandcat** [comment]
となると以下で実装できるか試す

■ Updating your App Over-the-Air
https://docs.expo.dev/bare/updating-your-app/

**Comment by wheatandcat** [comment]
メンテンスモードの表示を作成して、それに切り替えてpublishすればできそうだけど、

https://zenn.dev/marin_a___/articles/7eec197a8c3579

ダウンロードが入ることを考えると単純にFirestoreで実装する方が良さそう
