### ISSUE TITLE
react-navigation v6にバージョンアップ

### ISSUE THREAD

**Issue by wheatandcat** [wheatandcat/memoir#118]
## 対応内容

v5系からのマイグレーション
https://reactnavigation.org/docs/upgrading-from-5.x/

**Comment by wheatandcat** [comment]
```
Found screens with the same name nested inside one another. Check:

Home, Home > Home

This can cause confusing behavior during navigation. Consider using unique names for each screen instead.
at node_modules/@sentry/utils/dist/instrument.js:111:20 in <anonymous>
at src/Router.tsx:5:0 in <global>
at node_modules/@react-navigation/core/src/useOnAction.tsx:135:9 in React.useCallback$argument_0
```

たぶん、これを使う
https://reactnavigation.org/docs/upgrading-from-5.x/#new-group-component
